console.log("Typescripte girdik");
console.log("Zafer Günay Önalan");
var age = 29;
var firstname = "Zafer Günay";
var lastname = "Önalan";
var isUpdated = true;
var employeeName = "Zafer Günay";
var employeeDept = "Software Developer";
var employeeDesc = "".concat(employeeName, " works in the ").concat(employeeDept, " department");
console.log(employeeDesc);
